### ISSUE TITLE
TA3 API Client: Error producing solution results

### ISSUE THREAD

**Issue by Hector-hedb12** [HDI-Project/mit-d3m-ta2#4]
The [TA3APIClient.get_produce_solution_results(...)](https://github.com/HDI-Project/mit-d3m-ta2/blob/master/ta2/ta3/client.py#L335) method is not adding results to the `results` variable, therefore, it always returns `[]`:

```python
    def get_produce_solution_results(self, request_id):
        ...
        results = []
        for result in self.stub.GetProduceSolutionResults(request):
            LOGGER.debug("%s: %s", result.__class__.__name__, result)

        return results
```

**Comment by csala** [comment]
This seems to not be a problem anymore. Closing for now.
